// ignore_for_file: non_constant_identifier_names

import 'ShaderChunk/alphamap_fragment.glsl.dart';
import 'ShaderChunk/alphamap_pars_fragment.glsl.dart';
import 'ShaderChunk/alphatest_fragment.glsl.dart';
import 'ShaderChunk/alphatest_pars_fragment.glsl.dart';
import 'ShaderChunk/aomap_fragment.glsl.dart';
import 'ShaderChunk/aomap_pars_fragment.glsl.dart';
import 'ShaderChunk/begin_vertex.glsl.dart';
import 'ShaderChunk/beginnormal_vertex.glsl.dart';
import 'ShaderChunk/bsdfs.glsl.dart';
import 'ShaderChunk/bumpmap_pars_fragment.glsl.dart';
import 'ShaderChunk/clearcoat_normal_fragment_begin.glsl.dart';
import 'ShaderChunk/clearcoat_normal_fragment_maps.glsl.dart';
import 'ShaderChunk/clearcoat_pars_fragment.glsl.dart';
import 'ShaderChunk/clipping_planes_fragment.glsl.dart';
import 'ShaderChunk/clipping_planes_pars_fragment.glsl.dart';
import 'ShaderChunk/clipping_planes_pars_vertex.glsl.dart';
import 'ShaderChunk/clipping_planes_vertex.glsl.dart';
import 'ShaderChunk/color_fragment.glsl.dart';
import 'ShaderChunk/color_pars_fragment.glsl.dart';
import 'ShaderChunk/color_pars_vertex.glsl.dart';
import 'ShaderChunk/color_vertex.glsl.dart';
import 'ShaderChunk/common.glsl.dart';
import 'ShaderChunk/cube_uv_reflection_fragment.glsl.dart';
import 'ShaderChunk/defaultnormal_vertex.glsl.dart';
import 'ShaderChunk/displacementmap_pars_vertex.glsl.dart';
import 'ShaderChunk/displacementmap_vertex.glsl.dart';
import 'ShaderChunk/dithering_fragment.glsl.dart';
import 'ShaderChunk/dithering_pars_fragment.glsl.dart';
import 'ShaderChunk/emissivemap_fragment.glsl.dart';
import 'ShaderChunk/emissivemap_pars_fragment.glsl.dart';
import 'ShaderChunk/encodings_fragment.glsl.dart';
import 'ShaderChunk/encodings_pars_fragment.glsl.dart';
import 'ShaderChunk/envmap_common_pars_fragment.glsl.dart';
import 'ShaderChunk/envmap_fragment.glsl.dart';
import 'ShaderChunk/envmap_pars_fragment.glsl.dart';
import 'ShaderChunk/envmap_pars_vertex.glsl.dart';
import 'ShaderChunk/envmap_physical_pars_fragment.glsl.dart';
import 'ShaderChunk/envmap_vertex.glsl.dart';
import 'ShaderChunk/fog_fragment.glsl.dart';
import 'ShaderChunk/fog_pars_fragment.glsl.dart';
import 'ShaderChunk/fog_pars_vertex.glsl.dart';
import 'ShaderChunk/fog_vertex.glsl.dart';
import 'ShaderChunk/gradientmap_pars_fragment.glsl.dart';
import 'ShaderChunk/lightmap_fragment.glsl.dart';
import 'ShaderChunk/lightmap_pars_fragment.glsl.dart';
import 'ShaderChunk/lights_fragment_begin.glsl.dart';
import 'ShaderChunk/lights_fragment_end.glsl.dart';
import 'ShaderChunk/lights_fragment_maps.glsl.dart';
import 'ShaderChunk/lights_lambert_vertex.glsl.dart';
import 'ShaderChunk/lights_pars_begin.glsl.dart';
import 'ShaderChunk/lights_phong_fragment.glsl.dart';
import 'ShaderChunk/lights_phong_pars_fragment.glsl.dart';
import 'ShaderChunk/lights_physical_fragment.glsl.dart';
import 'ShaderChunk/lights_physical_pars_fragment.glsl.dart';
import 'ShaderChunk/lights_toon_fragment.glsl.dart';
import 'ShaderChunk/lights_toon_pars_fragment.glsl.dart';
import 'ShaderChunk/logdepthbuf_fragment.glsl.dart';
import 'ShaderChunk/logdepthbuf_pars_fragment.glsl.dart';
import 'ShaderChunk/logdepthbuf_pars_vertex.glsl.dart';
import 'ShaderChunk/logdepthbuf_vertex.glsl.dart';
import 'ShaderChunk/map_fragment.glsl.dart';
import 'ShaderChunk/map_pars_fragment.glsl.dart';
import 'ShaderChunk/map_particle_fragment.glsl.dart';
import 'ShaderChunk/map_particle_pars_fragment.glsl.dart';
import 'ShaderChunk/metalnessmap_fragment.glsl.dart';
import 'ShaderChunk/metalnessmap_pars_fragment.glsl.dart';
import 'ShaderChunk/morphnormal_vertex.glsl.dart';
import 'ShaderChunk/morphtarget_pars_vertex.glsl.dart';
import 'ShaderChunk/morphtarget_vertex.glsl.dart';
import 'ShaderChunk/normal_fragment_begin.glsl.dart';
import 'ShaderChunk/normal_fragment_maps.glsl.dart';
import 'ShaderChunk/normal_pars_fragment.glsl.dart';
import 'ShaderChunk/normal_pars_vertex.glsl.dart';
import 'ShaderChunk/normal_vertex.glsl.dart';
import 'ShaderChunk/normalmap_pars_fragment.glsl.dart';
import 'ShaderChunk/output_fragment.glsl.dart';
import 'ShaderChunk/packing.glsl.dart';
import 'ShaderChunk/premultiplied_alpha_fragment.glsl.dart';
import 'ShaderChunk/project_vertex.glsl.dart';
import 'ShaderChunk/roughnessmap_fragment.glsl.dart';
import 'ShaderChunk/roughnessmap_pars_fragment.glsl.dart';
import 'ShaderChunk/shadowmap_pars_fragment.glsl.dart';
import 'ShaderChunk/shadowmap_pars_vertex.glsl.dart';
import 'ShaderChunk/shadowmap_vertex.glsl.dart';
import 'ShaderChunk/shadowmask_pars_fragment.glsl.dart';
import 'ShaderChunk/skinbase_vertex.glsl.dart';
import 'ShaderChunk/skinning_pars_vertex.glsl.dart';
import 'ShaderChunk/skinning_vertex.glsl.dart';
import 'ShaderChunk/skinnormal_vertex.glsl.dart';
import 'ShaderChunk/specularmap_fragment.glsl.dart';
import 'ShaderChunk/specularmap_pars_fragment.glsl.dart';
import 'ShaderChunk/tonemapping_fragment.glsl.dart';
import 'ShaderChunk/tonemapping_pars_fragment.glsl.dart';
import 'ShaderChunk/transmission_fragment.glsl.dart';
import 'ShaderChunk/transmission_pars_fragment.glsl.dart';
import 'ShaderChunk/uv2_pars_fragment.glsl.dart';
import 'ShaderChunk/uv2_pars_vertex.glsl.dart';
import 'ShaderChunk/uv2_vertex.glsl.dart';
import 'ShaderChunk/uv_pars_fragment.glsl.dart';
import 'ShaderChunk/uv_pars_vertex.glsl.dart';
import 'ShaderChunk/uv_vertex.glsl.dart';
import 'ShaderChunk/worldpos_vertex.glsl.dart';

import 'shader_lib/background.glsl.dart' as background;
import 'shader_lib/cube.glsl.dart' as cube;
import 'shader_lib/depth.glsl.dart' as depth;
import 'shader_lib/distanceRGBA.glsl.dart' as distanceRGBA;
import 'shader_lib/equirect.glsl.dart' as equirect;
import 'shader_lib/linedashed.glsl.dart' as linedashed;
import 'shader_lib/meshbasic.glsl.dart' as meshbasic;
import 'shader_lib/meshlambert.glsl.dart' as meshlambert;
import 'shader_lib/meshmatcap.glsl.dart' as meshmatcap;
import 'shader_lib/meshnormal.glsl.dart' as meshnormal;
import 'shader_lib/meshphong.glsl.dart' as meshphong;
import 'shader_lib/meshphysical.glsl.dart' as meshphysical;
import 'shader_lib/meshtoon.glsl.dart' as meshtoon;
import 'shader_lib/points.glsl.dart' as points;
import 'shader_lib/shadow.glsl.dart' as shadow;
import 'shader_lib/sprite.glsl.dart' as sprite;

class ShaderChunk {
  String alphamap_fragment = alphamap_fragment_glsl;
  String alphamap_pars_fragment = alphamap_pars_fragment_glsl;
  String alphatest_fragment = alphatest_fragment_glsl;
  String alphatest_pars_fragment = alphatest_pars_fragment_glsl;
  String aomap_fragment = aomap_fragment_glsl;
  String aomap_pars_fragment = aomap_pars_fragment_glsl;
  String begin_vertex = begin_vertex_glsl;
  String beginnormal_vertex = beginnormal_vertex_glsl;
  String bsdfs = bsdfs_glsl;
  String bumpmap_pars_fragment = bumpmap_pars_fragment_glsl;
  String clipping_planes_fragment = clipping_planes_fragment_glsl;
  String clipping_planes_pars_fragment = clipping_planes_pars_fragment_glsl;
  String clipping_planes_pars_vertex = clipping_planes_pars_vertex_glsl;
  String clipping_planes_vertex = clipping_planes_vertex_glsl;
  String color_fragment = color_fragment_glsl;
  String color_pars_fragment = color_pars_fragment_glsl;
  String color_pars_vertex = color_pars_vertex_glsl;
  String color_vertex = color_vertex_glsl;
  String common = common_glsl;
  String cube_uv_reflection_fragment = cube_uv_reflection_fragment_glsl;
  String defaultnormal_vertex = defaultnormal_vertex_glsl;
  String displacementmap_pars_vertex = displacementmap_pars_vertex_glsl;
  String displacementmap_vertex = displacementmap_vertex_glsl;
  String emissivemap_fragment = emissivemap_fragment_glsl;
  String emissivemap_pars_fragment = emissivemap_pars_fragment_glsl;
  String encodings_fragment = encodings_fragment_glsl;
  String encodings_pars_fragment = encodings_pars_fragment_glsl;
  String envmap_fragment = envmap_fragment_glsl;
  String envmap_common_pars_fragment = envmap_common_pars_fragment_glsl;
  String envmap_pars_fragment = envmap_pars_fragment_glsl;
  String envmap_pars_vertex = envmap_pars_vertex_glsl;
  String envmap_physical_pars_fragment = envmap_physical_pars_fragment_glsl;
  String envmap_vertex = envmap_vertex_glsl;
  String fog_vertex = fog_vertex_glsl;
  String fog_pars_vertex = fog_pars_vertex_glsl;
  String fog_fragment = fog_fragment_glsl;
  String fog_pars_fragment = fog_pars_fragment_glsl;
  String gradientmap_pars_fragment = gradientmap_pars_fragment_glsl;
  String lightmap_fragment = lightmap_fragment_glsl;
  String lightmap_pars_fragment = lightmap_pars_fragment_glsl;
  String lights_lambert_vertex = lights_lambert_vertex_glsl;
  String lights_pars_begin = lights_pars_begin_glsl;
  String lights_toon_fragment = lights_toon_fragment_glsl;
  String lights_toon_pars_fragment = lights_toon_pars_fragment_glsl;
  String lights_phong_fragment = lights_phong_fragment_glsl;
  String lights_phong_pars_fragment = lights_phong_pars_fragment_glsl;
  String lights_physical_fragment = lights_physical_fragment_glsl;
  String lights_physical_pars_fragment = lights_physical_pars_fragment_glsl;
  String lights_fragment_begin = lights_fragment_begin_glsl;
  String lights_fragment_maps = lights_fragment_maps_glsl;
  String lights_fragment_end = lights_fragment_end_glsl;
  String logdepthbuf_fragment = logdepthbuf_fragment_glsl;
  String logdepthbuf_pars_fragment = logdepthbuf_pars_fragment_glsl;
  String logdepthbuf_pars_vertex = logdepthbuf_pars_vertex_glsl;
  String logdepthbuf_vertex = logdepthbuf_vertex_glsl;
  String map_fragment = map_fragment_glsl;
  String map_pars_fragment = map_pars_fragment_glsl;
  String map_particle_fragment = map_particle_fragment_glsl;
  String map_particle_pars_fragment = map_particle_pars_fragment_glsl; //
  String metalnessmap_fragment = metalnessmap_fragment_glsl;
  String metalnessmap_pars_fragment = metalnessmap_pars_fragment_glsl;
  String morphnormal_vertex = morphnormal_vertex_glsl;
  String morphtarget_pars_vertex = morphtarget_pars_vertex_glsl;
  String morphtarget_vertex = morphtarget_vertex_glsl;
  String normal_fragment_begin = normal_fragment_begin_glsl;
  String normal_fragment_maps = normal_fragment_maps_glsl;
  String normal_pars_fragment = normal_pars_fragment_glsl;
  String normal_pars_vertex = normal_pars_vertex_glsl;
  String normal_vertex = normal_vertex_glsl;
  String normalmap_pars_fragment = normalmap_pars_fragment_glsl;
  String clearcoat_normal_fragment_begin = clearcoat_normal_fragment_begin_glsl;
  String clearcoat_normal_fragment_maps = clearcoat_normal_fragment_maps_glsl;
  String clearcoat_pars_fragment = clearcoat_pars_fragment_glsl;
  String output_fragment = output_fragment_glsl;
  String packing = packing_glsl;
  String premultiplied_alpha_fragment = premultiplied_alpha_fragment_glsl;
  String project_vertex = project_vertex_glsl;
  String dithering_fragment = dithering_fragment_glsl;
  String dithering_pars_fragment = dithering_pars_fragment_glsl;
  String roughnessmap_fragment = roughnessmap_fragment_glsl;
  String roughnessmap_pars_fragment = roughnessmap_pars_fragment_glsl;
  String shadowmap_pars_fragment = shadowmap_pars_fragment_glsl;
  String shadowmap_pars_vertex = shadowmap_pars_vertex_glsl;
  String shadowmap_vertex = shadowmap_vertex_glsl;
  String shadowmask_pars_fragment = shadowmask_pars_fragment_glsl;
  String skinbase_vertex = skinbase_vertex_glsl;
  String skinning_pars_vertex = skinning_pars_vertex_glsl;
  String skinning_vertex = skinning_vertex_glsl;
  String skinnormal_vertex = skinnormal_vertex_glsl;
  String specularmap_fragment = specularmap_fragment_glsl;
  String specularmap_pars_fragment = specularmap_pars_fragment_glsl;
  String tonemapping_fragment = tonemapping_fragment_glsl;
  String tonemapping_pars_fragment = tonemapping_pars_fragment_glsl;
  String transmission_fragment = transmission_fragment_glsl;
  String transmission_pars_fragment = transmission_pars_fragment_glsl;
  String uv_pars_fragment = uv_pars_fragment_glsl;
  String uv_pars_vertex = uv_pars_vertex_glsl;
  String uv_vertex = uv_vertex_glsl;
  String uv2_pars_fragment = uv2_pars_fragment_glsl;
  String uv2_pars_vertex = uv2_pars_vertex_glsl;
  String uv2_vertex = uv2_vertex_glsl;
  String worldpos_vertex = worldpos_vertex_glsl;

  String background_vert = background.vertex;
  String background_frag = background.fragment;
  String cube_vert = cube.vertex;
  String cube_frag = cube.fragment;
  String depth_vert = depth.vertex;
  String depth_frag = depth.fragment;
  String distanceRGBA_vert = distanceRGBA.vertex;
  String distanceRGBA_frag = distanceRGBA.fragment;
  String equirect_vert = equirect.vertex;
  String equirect_frag = equirect.fragment;
  String linedashed_vert = linedashed.vertex;
  String linedashed_frag = linedashed.fragment;
  String meshbasic_vert = meshbasic.vertex;
  String meshbasic_frag = meshbasic.fragment;
  String meshlambert_vert = meshlambert.vertex;
  String meshlambert_frag = meshlambert.fragment;
  String meshmatcap_vert = meshmatcap.vertex;
  String meshmatcap_frag = meshmatcap.fragment;
  String meshnormal_vert = meshnormal.vertex;
  String meshnormal_frag = meshnormal.fragment;
  String meshphong_vert = meshphong.vertex;
  String meshphong_frag = meshphong.fragment;
  String meshphysical_vert = meshphysical.vertex;
  String meshphysical_frag = meshphysical.fragment;
  String meshtoon_vert = meshtoon.vertex;
  String meshtoon_frag = meshtoon.fragment;
  String points_vert = points.vertex;
  String points_frag = points.fragment;
  String shadow_vert = shadow.vertex;
  String shadow_frag = shadow.fragment;
  String sprite_vert = sprite.vertex;
  String sprite_frag = sprite.fragment;

  operator [](String key) {
    return this[key];
  }
}
